# Eval
this notebook is for calling supporting scripts to derive and present evaluations in an accessible fashion.

# 1 Imports & Setup

In [1]:
import sys, pathlib

PROJECT_ROOT = pathlib.Path('.').resolve()
while not (PROJECT_ROOT / '.git').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import torch
import torchaudio
import soundfile as sf
from transformers import AutoProcessor, AutoModelForCTC

/home/peter/miniconda3/envs/thesis/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from scripts.eval.fetch_annotations import fetch_annotations
from scripts.eval.eval import (
    evaluate_mispronunciation_detection, 
    show_alignment, 
    show_alignment_html, 
    greedy_ctc_phones
)

from scripts.data_handling.collapse_phonemes import collapse_phones
from scripts.asr_system.ensemble.run_inference import run_ensemble_inference
from scripts.asr_system.ensemble.ensemble import (
    build_ru_ipa_dict,
    build_pal_set,
    frame_gibbs_confidence,
)

In [4]:
DEVICE    =  "cpu" # "cuda" if torch.cuda.is_available() else "cpu" decomment if running on kaggle.
AUDIO_DIR = PROJECT_ROOT / "data" / "fleurs" / "audio" / "test" # point to kaggle dataset if using on there.
ANN_CACHE = PROJECT_ROOT / "data" / "eval" / "annotations_cache.json" # point to kaggle dataset.
IMAGES_DIR = PROJECT_ROOT / "paper" / "0000-CadyThesis-Draft" / "images"

GA_MODEL_ID           = "duck-hug-567/xls-r-300m-gaphon-full-collapsed"
EN_MODEL_ID           = "duck-hug-567/xls-r-300m-engphon-collapsed"
RU_MODEL_ID           = "snu-nia-12/wav2vec-large-xlsr-53_nia12_phone-nsu-ai-_russian"  # set to model ID string to enable Russian specialist
L2_MODEL_ID           = "duck-hug-567/xls-r-300m-paired"  # synthetic-augmented model (paired training)
L2_BASELINE_MODEL_ID  = None  # synthetic-augmented model (unpaired baseline)
COMBINED_MODEL_ID  = None  # single model trained on Irish+English data combined

print(f"Device:     {DEVICE}")
print(f"Images dir: {IMAGES_DIR}")

Device:     cpu
Images dir: /home/peter/Desktop/thesis/ThesisProject/paper/0000-CadyThesis-Draft/images

In [5]:
ga_processor = AutoProcessor.from_pretrained(GA_MODEL_ID)
ga_model     = AutoModelForCTC.from_pretrained(GA_MODEL_ID).to(DEVICE).eval()

en_processor = AutoProcessor.from_pretrained(EN_MODEL_ID)
en_model     = AutoModelForCTC.from_pretrained(EN_MODEL_ID).to(DEVICE).eval()

ru_processor = ru_model = None
if RU_MODEL_ID:
    ru_processor = AutoProcessor.from_pretrained(RU_MODEL_ID)
    ru_model     = AutoModelForCTC.from_pretrained(RU_MODEL_ID).to(DEVICE).eval()

l2_processor = l2_model = None
if L2_MODEL_ID:
    l2_processor = AutoProcessor.from_pretrained(L2_MODEL_ID)
    l2_model     = AutoModelForCTC.from_pretrained(L2_MODEL_ID).to(DEVICE).eval()

l2_baseline_processor = l2_baseline_model = None
if L2_BASELINE_MODEL_ID:
    l2_baseline_processor = AutoProcessor.from_pretrained(L2_BASELINE_MODEL_ID)
    l2_baseline_model     = AutoModelForCTC.from_pretrained(L2_BASELINE_MODEL_ID).to(DEVICE).eval()

combined_processor = combined_model = None
if COMBINED_MODEL_ID:
    combined_processor = AutoProcessor.from_pretrained(COMBINED_MODEL_ID)
    combined_model     = AutoModelForCTC.from_pretrained(COMBINED_MODEL_ID).to(DEVICE).eval()

print("Models loaded.")

Loading weights: 100%|██████████| 424/424 [00:00<00:00, 485.23it/s, Materializing param=wav2vec2.masked_spec_embed]
Loading weights: 100%|██████████| 424/424 [00:00<00:00, 670.58it/s, Materializing param=wav2vec2.masked_spec_embed]
Loading weights: 100%|██████████| 424/424 [00:00<00:00, 889.57it/s, Materializing param=wav2vec2.masked_spec_embed]
Loading weights: 100%|██████████| 424/424 [00:00<00:00, 708.88it/s, Materializing param=wav2vec2.masked_spec_embed]

Models loaded.

# 2 Load Data
Annotations (FLEURS Gold standard), Ulster transcriptions (canonical), audio (FLEURS eval audio)

In [6]:
records = fetch_annotations(cache_path=ANN_CACHE, refresh=True)

print(f"Loaded {len(records)} annotated utterances")
print(f"Total canonical phones : {sum(len(r['canonical']) for r in records)}")
print(f"Total gold phones      : {sum(len(r['gold']) for r in records)}")

Loaded 24 annotated utterances
Total canonical phones : 2379
Total gold phones      : 2442

## 2.1 Normalise

Apply `collapse_phones` to canonical and gold so all three sequences (canonical, gold, asr)
share the same phone space — the ga model's collapsed vocab.
The asr output from inference is already in this space by construction.

In [7]:
for r in records:
    r['canonical'] = collapse_phones(r['canonical'])
    r['gold']      = collapse_phones(r['gold'])

worth noting that this normalization is performed in place, so if I need access to the originals, I need ot reload the fetching.

## 2.2 Sanity check

In [8]:
for r in records:
    print(f"\n{r['audio_id']}")
    print(f"  canonical ({len(r['canonical'])}): {' '.join(r['canonical'][:10])} ...")
    print(f"  gold      ({len(r['gold'])}): {' '.join(r['gold'][:10])} ...")

10090378450980723387
  canonical (53): i s ia d n ə lʲ oː nʲ n ...
  gold      (51): i s i d lʲ oi nʲ n a x ...

10045899353945045473
  canonical (114): i s eː o v ə pʲ ɾʲ iː v ...
  gold      (121): i s eː ɑ w ɑ ʃ ə a n ...

10113135482749057387
  canonical (224): h ua ɾʲ ə ʃ c iː t ai dʲ ...
  gold      (242): h ua ɾʲ s iː g t ai dʲ oː ...

10118867771707376132
  canonical (162): ɡ ə ɟ i nʲ ə ɾ a l t ...
  gold      (167): ɣ ɑ ɣ e nʲ ə ɾ a l t ...

10200386800286571225
  canonical (82): x o mʲ a d ə n p aː ɾ ...
  gold      (94): k ə vʲ a d p aː ɾ tʲ iː ...

10206677242691936838
  canonical (46): i s a s ʃ i nʲ ə h aː ...
  gold      (46): i s a s ʃ i nʲ ə h aː ...

1023087891474057557
  canonical (97): e ɾʲ ə n l aː vʲ e lʲ ə ...
  gold      (115): e ɹ ə n l aː v e lʲ e ...

10233874176421692304
  canonical (37): i nʲ eː ɾ a dʲ tʲ e ə n ...
  gold      (38): i n ɑː ɹ ɐ d ə n t eɪ ...

10239398288528692924
  canonical (100): t aː k oː j eː n uː n ə ...
  gold      (97): t aː k oː j eː n uː n a ...

10243049501972270976
  canonical (105): nʲ iː m oː f au l ə m ə ...
  gold      (102): nʲ iː m oː f o l m ə eː ...

10266820967862372597
  canonical (74): mʲ a s k ɣ aː pʲ h uː d ...
  gold      (78): mʲ a s k j aː pʲ h u d ...

10271786421440476629
  canonical (100): t aː k oː j eː n uː n ə ...
  gold      (106): t aː k oː v lʲ eː n uː v ...

10293194478892841169
  canonical (82): s k iː lʲ uː ʃ eː j iˑə l ...
  gold      (77): s k iː lʲ uː ʃ eː j iˑə l ...

10304378288628596403
  canonical (49): t a ʃ pʲ a n ə n t uˑə ...
  gold      (46): t a ʃ pʲ ə n ə n t uˑə ...

10444116527668746262
  canonical (99): f iː ç a n k o c i ʃ ...
  gold      (100): f iː x eːnʲ n ɧ i ʃ ə v ...

10573678544490813685
  canonical (84): i s fʲ eː dʲ ə ɾʲ n a h ...
  gold      (80): i s fʲ eː dʲ ə ɾʲ n a h ...

10629633157023963485
  canonical (112): c eː ɡ ə vʲ f i lʲ ɡ o ...
  gold      (119): k ei ɡ o w i lʲ ɡ o m ...

10709733798173736804
  canonical (126): t o ʃ c n a h ɾ vʲ f ...
  gold      (127): t o ʃ c n a ɾ o f ai ...

10750793998905071751
  canonical (90): i s p ɾ oː t o nʲ ia d ...
  gold      (95): i s p ɾ oː t o nʲ ia d ...

10759012859139903595
  canonical (61): i s eː m a d ə ɡ ə s ...
  gold      (59): i s eː m a d ə ɡ a s ...

10767741613619699126
  canonical (163): t aː ə n eː mʲ ç eː ɾ n ...
  gold      (169): t æː e n ai ç eː ɾ n ə ...

10790624209743962917
  canonical (113): ə ɡ ə s iː t oː k ə e ...
  gold      (114): a ɡ ə s iː t oː g uː n ...

10913760967925440736
  canonical (46): n aː mʲ i lʲ tʲ ə ɾ ə n ...
  gold      (47): n aː mʲ i lʲ tʲ aː ɹ ə n ...

10938929585198562226
  canonical (160): oː n tʲ ʃ a n a mʲ ʃ ə ...
  gold      (152): oː n ʃ aː n aː mʲ ʃ ə ɹ ...

# 3 Inference

## 3.1 Ensemble

In [9]:
ensemble_2way_records = run_ensemble_inference(
    records,
    ga_processor, ga_model,
    en_processor, en_model,
    ru_processor=None, ru_model=None,
    audio_dir=AUDIO_DIR,
    device=DEVICE,
)
print(f"2-way done. {len(ensemble_2way_records)} utterances.")

ensemble_2way_pooled_records = run_ensemble_inference(
    records,
    ga_processor, ga_model,
    en_processor, en_model,
    ru_processor=None, ru_model=None,
    pool_ga=True,
    audio_dir=AUDIO_DIR,
    device=DEVICE,
)
print(f"2-way (pooled) done. {len(ensemble_2way_pooled_records)} utterances.")

ensemble_3way_records = None
ensemble_3way_pooled_records = None
if ru_processor is not None:
    ensemble_3way_records = run_ensemble_inference(
        records,
        ga_processor, ga_model,
        en_processor, en_model,
        ru_processor=ru_processor, ru_model=ru_model,
        audio_dir=AUDIO_DIR,
        device=DEVICE,
    )
    print(f"3-way done. {len(ensemble_3way_records)} utterances.")

    ensemble_3way_pooled_records = run_ensemble_inference(
        records,
        ga_processor, ga_model,
        en_processor, en_model,
        ru_processor=ru_processor, ru_model=ru_model,
        pool_ga=True,
        audio_dir=AUDIO_DIR,
        device=DEVICE,
    )
    print(f"3-way (pooled) done. {len(ensemble_3way_pooled_records)} utterances.")
else:
    print("RU_MODEL_ID not set — 3-way ensembles skipped.")

[1/24] 10090378450980723387 (53 phones)...
[2/24] 10045899353945045473 (114 phones)...
[3/24] 10113135482749057387 (224 phones)...
[4/24] 10118867771707376132 (162 phones)...
[5/24] 10200386800286571225 (82 phones)...
[6/24] 10206677242691936838 (46 phones)...
[7/24] 1023087891474057557 (97 phones)...
[8/24] 10233874176421692304 (37 phones)...
[9/24] 10239398288528692924 (100 phones)...
[10/24] 10243049501972270976 (105 phones)...
[11/24] 10266820967862372597 (74 phones)...
[12/24] 10271786421440476629 (100 phones)...
[13/24] 10293194478892841169 (82 phones)...
[14/24] 10304378288628596403 (49 phones)...
[15/24] 10444116527668746262 (99 phones)...
[16/24] 10573678544490813685 (84 phones)...
[17/24] 10629633157023963485 (112 phones)...
[18/24] 10709733798173736804 (126 phones)...
[19/24] 10750793998905071751 (90 phones)...
[20/24] 10759012859139903595 (61 phones)...
[21/24] 10767741613619699126 (163 phones)...
[22/24] 10790624209743962917 (113 phones)...
[23/24] 10913760967925440736 (46 phones)...
[24/24] 10938929585198562226 (160 phones)...
2-way done. 24 utterances.
[1/24] 10090378450980723387 (53 phones)...
[2/24] 10045899353945045473 (114 phones)...
[3/24] 10113135482749057387 (224 phones)...
[4/24] 10118867771707376132 (162 phones)...
[5/24] 10200386800286571225 (82 phones)...
[6/24] 10206677242691936838 (46 phones)...
[7/24] 1023087891474057557 (97 phones)...
[8/24] 10233874176421692304 (37 phones)...
[9/24] 10239398288528692924 (100 phones)...
[10/24] 10243049501972270976 (105 phones)...
[11/24] 10266820967862372597 (74 phones)...
[12/24] 10271786421440476629 (100 phones)...
[13/24] 10293194478892841169 (82 phones)...
[14/24] 10304378288628596403 (49 phones)...
[15/24] 10444116527668746262 (99 phones)...
[16/24] 10573678544490813685 (84 phones)...
[17/24] 10629633157023963485 (112 phones)...
[18/24] 10709733798173736804 (126 phones)...
[19/24] 10750793998905071751 (90 phones)...
[20/24] 10759012859139903595 (61 phones)...
[21/24] 10767741613619699126 (163 phones)...
[22/24] 10790624209743962917 (113 phones)...
[23/24] 10913760967925440736 (46 phones)...
[24/24] 10938929585198562226 (160 phones)...
2-way (pooled) done. 24 utterances.
[1/24] 10090378450980723387 (53 phones)...
[2/24] 10045899353945045473 (114 phones)...
[3/24] 10113135482749057387 (224 phones)...
[4/24] 10118867771707376132 (162 phones)...
[5/24] 10200386800286571225 (82 phones)...
[6/24] 10206677242691936838 (46 phones)...
[7/24] 1023087891474057557 (97 phones)...
[8/24] 10233874176421692304 (37 phones)...
[9/24] 10239398288528692924 (100 phones)...
[10/24] 10243049501972270976 (105 phones)...
[11/24] 10266820967862372597 (74 phones)...
[12/24] 10271786421440476629 (100 phones)...
[13/24] 10293194478892841169 (82 phones)...
[14/24] 10304378288628596403 (49 phones)...
[15/24] 10444116527668746262 (99 phones)...
[16/24] 10573678544490813685 (84 phones)...
[17/24] 10629633157023963485 (112 phones)...
[18/24] 10709733798173736804 (126 phones)...
[19/24] 10750793998905071751 (90 phones)...
[20/24] 10759012859139903595 (61 phones)...
[21/24] 10767741613619699126 (163 phones)...
[22/24] 10790624209743962917 (113 phones)...
[23/24] 10913760967925440736 (46 phones)...
[24/24] 10938929585198562226 (160 phones)...
3-way done. 24 utterances.
[1/24] 10090378450980723387 (53 phones)...
[2/24] 10045899353945045473 (114 phones)...
[3/24] 10113135482749057387 (224 phones)...
[4/24] 10118867771707376132 (162 phones)...
[5/24] 10200386800286571225 (82 phones)...
[6/24] 10206677242691936838 (46 phones)...
[7/24] 1023087891474057557 (97 phones)...
[8/24] 10233874176421692304 (37 phones)...
[9/24] 10239398288528692924 (100 phones)...
[10/24] 10243049501972270976 (105 phones)...
[11/24] 10266820967862372597 (74 phones)...
[12/24] 10271786421440476629 (100 phones)...
[13/24] 10293194478892841169 (82 phones)...
[14/24] 10304378288628596403 (49 phones)...
[15/24] 10444116527668746262 (99 phones)...
[16/24] 10573678544490813685 (84 phones)...
[17/24] 10629633157023963485 (112 phones)...
[18/24] 10709733798173736804 (126 phones)...
[19/24] 10750793998905071751 (90 phones)...
[20/24] 10759012859139903595 (61 phones)...
[21/24] 10767741613619699126 (163 phones)...
[22/24] 10790624209743962917 (113 phones)...
[23/24] 10913760967925440736 (46 phones)...
[24/24] 10938929585198562226 (160 phones)...
3-way (pooled) done. 24 utterances.

## 3.2 Synthetic-augmentation

### 3.2.1 Synthetic-augmented model (adversarial sampling)

In [10]:
l2_records = None

if l2_model is not None:
    l2_records = []
    for r in records:
        audio_path = AUDIO_DIR / f"{r['audio_id']}.wav"
        data, sr = sf.read(audio_path, dtype="float32", always_2d=False)
        if sr != 16000:
            data = torchaudio.functional.resample(torch.from_numpy(data).unsqueeze(0), sr, 16000).squeeze(0).numpy()
        asr = collapse_phones(greedy_ctc_phones(l2_processor, l2_model, data, device=DEVICE))
        result = dict(r)
        result["asr"] = asr
        l2_records.append(result)
    print(f"Done. {len(l2_records)} utterances inferred.")
else:
    print("L2_MODEL_ID not set — skipping. Set it in the config cell when the model is ready.")

Done. 24 utterances inferred.

### 3.2.2 Synthetic-augmented model (unpaired baseline)

Same architecture as 3.2.1 but trained on synthetic and canonical data as independent instances,
without adversarial canonical/L2 pairing. Serves as an ablation to isolate the contribution
of the pairing strategy.

In [11]:
l2_baseline_records = None

if l2_baseline_model is not None:
    l2_baseline_records = []
    for r in records:
        audio_path = AUDIO_DIR / f"{r['audio_id']}.wav"
        data, sr = sf.read(audio_path, dtype="float32", always_2d=False)
        if sr != 16000:
            data = torchaudio.functional.resample(torch.from_numpy(data).unsqueeze(0), sr, 16000).squeeze(0).numpy()
        asr = collapse_phones(greedy_ctc_phones(l2_baseline_processor, l2_baseline_model, data, device=DEVICE))
        result = dict(r)
        result["asr"] = asr
        l2_baseline_records.append(result)
    print(f"Done. {len(l2_baseline_records)} utterances inferred.")
else:
    print("L2_BASELINE_MODEL_ID not set — skipping.")

L2_BASELINE_MODEL_ID not set — skipping.

## 3.3 Baselines

### 3.3.1 Irish-only (no augmentation)

The un-augmented baseline: plain CTC greedy decode from the Irish model alone,
no ensemble, no synthetic data. This is the starting point the L2-gen approach
builds on — everything else should beat this or the experiment hasn't worked.

In [12]:
irish_only_records = []
for r in records:
    audio_path = AUDIO_DIR / f"{r['audio_id']}.wav"
    data, sr = sf.read(audio_path, dtype="float32", always_2d=False)
    if sr != 16000:
        data = torchaudio.functional.resample(torch.from_numpy(data).unsqueeze(0), sr, 16000).squeeze(0).numpy()
    asr = collapse_phones(greedy_ctc_phones(ga_processor, ga_model, data, device=DEVICE))
    result = dict(r)
    result["asr"] = asr
    irish_only_records.append(result)
print(f"Done. {len(irish_only_records)} utterances inferred.")

Done. 24 utterances inferred.

### 3.3.2 Irish+English combined (single model)

Single model trained on the union of Irish and English phoneme data, without
ensemble architecture. Tests whether diverse training data alone accounts for
any improvement, or whether the per-span confidence gating of the ensemble is
what matters. Requires a separately trained model — set `L2_COMBINED_MODEL_ID`
when ready.

In [13]:
l2_combined_records = None

if combined_model is not None:
    l2_combined_records = []
    for r in records:
        audio_path = AUDIO_DIR / f"{r['audio_id']}.wav"
        data, sr = sf.read(audio_path, dtype="float32", always_2d=False)
        if sr != 16000:
            data = torchaudio.functional.resample(torch.from_numpy(data).unsqueeze(0), sr, 16000).squeeze(0).numpy()
        asr = collapse_phones(greedy_ctc_phones(combined_processor, combined_model, data, device=DEVICE))
        result = dict(r)
        result["asr"] = asr
        l2_combined_records.append(result)
    print(f"Done. {len(l2_combined_records)} utterances inferred.")
else:
    print("COMBINED_MODEL_ID not set — skipping.")

COMBINED_MODEL_ID not set — skipping.

# 4 Per item Eval

In [14]:
# Central registry — add or comment out systems here as models become available.
# Any system whose records are None is automatically skipped below.
SYSTEMS = {
    "Ensemble (2-way)":        ensemble_2way_records,
    "Ensemble (2-way, pooled)": ensemble_2way_pooled_records,
    "Ensemble (3-way)":        ensemble_3way_records,
    "Ensemble (3-way, pooled)": ensemble_3way_pooled_records,
    "L2 model (paired)":       l2_records,
    "L2 model (unpaired)":     l2_baseline_records,
    "Irish+English combined":  l2_combined_records,
    "Irish only (baseline)":   irish_only_records,
}

active_systems = {name: recs for name, recs in SYSTEMS.items() if recs is not None}
print("Active systems:", list(active_systems.keys()))

Active systems: ['Ensemble (2-way)', 'Ensemble (2-way, pooled)', 'Ensemble (3-way)', 'Ensemble (3-way, pooled)', 'L2 model (paired)', 'Irish only (baseline)']

In [15]:
rows = []
for system_name, system_records in active_systems.items():
    for r in system_records:
        metrics = evaluate_mispronunciation_detection(
            r['canonical'], r['gold'], r['asr']
        )
        rows.append({
            'system':   system_name,
            'audio_id': r['audio_id'],
            **metrics,
        })

per_utt_df = pd.DataFrame(rows)
per_utt_df

,system,audio_id,TR,FA,FR,TA,precision,recall,f1,false_acceptance_rate,false_rejection_rate,per,gold_insertions,asr_insertions
0,Ensemble (2-way),10090378450980723387,18,1,31,3,0.367347,0.947368,0.529412,0.052632,0.911765,1.679245,7,40
1,Ensemble (2-way),10045899353945045473,47,5,52,10,0.474747,0.903846,0.622517,0.096154,0.838710,1.429825,26,64
2,Ensemble (2-way),10113135482749057387,80,4,127,13,0.386473,0.952381,0.549828,0.047619,0.907143,1.593750,35,150
3,Ensemble (2-way),10118867771707376132,80,3,74,5,0.519481,0.963855,0.675105,0.036145,0.936709,1.876543,68,150
4,Ensemble (2-way),10200386800286571225,30,1,44,7,0.405405,0.967742,0.571429,0.032258,0.862745,1.426829,18,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,Irish only (baseline),10759012859139903595,13,7,21,20,0.382353,0.650000,0.481481,0.350000,0.512195,0.590164,2,2
140,Irish only (baseline),10767741613619699126,33,13,87,30,0.275000,0.717391,0.397590,0.282609,0.743590,1.092025,18,58
141,Irish only (baseline),10790624209743962917,19,15,45,34,0.296875,0.558824,0.387755,0.441176,0.569620,0.831858,13,30
142,Irish only (baseline),10913760967925440736,6,3,25,12,0.193548,0.666667,0.300000,0.333333,0.675676,0.978261,2,14
143,Irish only (baseline),10938929585198562226,31,9,54,66,0.364706,0.775000,0.496000,0.225000,0.450000,0.600000,4,11

In [28]:
show_alignment_html(irish_only_records[0])

In [27]:
show_alignment_html(l2_records[0])

In [26]:
show_alignment_html(ensemble_2way_records[0])

In [20]:
# inspect all records for a system
for r in l2_records:
    show_alignment_html(r)

# 5 Aggregate Metrics

Metrics are micro-aggregated: confusion counts (TR, FA, FR, TA) are summed
across all utterances per system, then precision/recall/F1/FAR/FRR are
re-derived from those totals. This gives longer utterances proportionally
more weight, which is what we want since we care about the performance on all phones.

PER is micro-aggregated the same way: total ASR errors / total canonical phones.

In [17]:
def _derived_metrics(TR, FA, FR, TA, total_errors, total_canonical):
    nan = float('nan')
    precision = TR / (TR + FR)            if (TR + FR) > 0 else nan
    recall    = TR / (TR + FA)            if (TR + FA) > 0 else nan
    f1        = (2 * precision * recall / (precision + recall)
                 if (precision + recall) > 0 else nan)
    far       = FA / (TR + FA)            if (TR + FA) > 0 else nan
    frr       = FR / (FR + TA)            if (FR + TA) > 0 else nan
    per       = total_errors / total_canonical if total_canonical > 0 else nan
    return dict(precision=precision, recall=recall, f1=f1,
                false_acceptance_rate=far, false_rejection_rate=frr, per=per)


agg_rows = []
for system_name, group in per_utt_df.groupby('system', sort=False):
    TR = group['TR'].sum()
    FA = group['FA'].sum()
    FR = group['FR'].sum()
    TA = group['TA'].sum()

    # PER micro-aggregation: recover error counts from per-utterance PER and
    # canonical length (= TR+FA+FR+TA since every canonical position is counted).
    canonical_lengths = group['TR'] + group['FA'] + group['FR'] + group['TA']
    total_canonical   = canonical_lengths.sum()
    total_errors      = (group['per'] * canonical_lengths).sum()

    agg_rows.append({
        'system': system_name,
        'TR': TR, 'FA': FA, 'FR': FR, 'TA': TA,
        'utterances': len(group),
        **_derived_metrics(TR, FA, FR, TA, total_errors, total_canonical),
    })

agg_df = pd.DataFrame(agg_rows).set_index('system')
agg_df

,TR,FA,FR,TA,utterances,precision,recall,f1,false_acceptance_rate,false_rejection_rate,per
system,,,,,,,,,,,
Ensemble (2-way),719,39,1429,192,24,0.334730,0.948549,0.494838,0.051451,0.881555,1.583438
"Ensemble (2-way, pooled)",713,45,1408,213,24,0.336162,0.940633,0.495311,0.059367,0.868600,1.538462
Ensemble (3-way),720,38,1429,192,24,0.335040,0.949868,0.495356,0.050132,0.881555,1.585540
"Ensemble (3-way, pooled)",714,44,1409,212,24,0.336317,0.941953,0.495661,0.058047,0.869217,1.540984
L2 model (paired),649,109,1162,459,24,0.358366,0.856201,0.505255,0.143799,0.716841,1.106768
Irish only (baseline),560,198,1061,560,24,0.345466,0.738786,0.470786,0.261214,0.654534,0.960908

In [23]:
# statistical significance testing using mcnemar
from scripts.eval.eval import mcnemar_mdd

baseline = irish_only_records
comparisons = {
    "Ensemble (2-way)":         ensemble_2way_records,
    "Ensemble (2-way, pooled)": ensemble_2way_pooled_records,
    "Ensemble (3-way)":         ensemble_3way_records,
    "Ensemble (3-way, pooled)": ensemble_3way_pooled_records,
    "L2 synth model": l2_records,
}

print(f"{'System':<30}  {'b':>5}  {'c':>5}  {'p-value':>10}")
print("-" * 55)
for name, sys_records in comparisons.items():
    if sys_records is None:
        continue
    res = mcnemar_mdd(sys_records, baseline)
    sig = "*" if res['pvalue'] < 0.05 else ""
    print(f"{name:<30}  {res['b']:>5}  {res['c']:>5}  {res['pvalue']:>10.4f} {sig}")

System                              b      c     p-value
-------------------------------------------------------
Ensemble (2-way)                  282    491      0.0000 *
Ensemble (2-way, pooled)          302    496      0.0000 *
Ensemble (3-way)                  282    490      0.0000 *
Ensemble (3-way, pooled)          302    496      0.0000 *
L2 synth model                    374    386      0.6899

In [24]:
for i, r in enumerate(ensemble_2way_records):
    lc, la = len(r['canonical']), len(r['asr'])
    if lc != la:
        print(f"[{i}] {r['audio_id']}: canonical={lc}, asr={la}")

In [ ]:
from scripts.eval.eval import align_phones

for r_ens, r_base in zip(ensemble_2way_records, irish_only_records):
    gt   = get_canonical_labels(r_ens['canonical'], r_ens['gold'])
    p_e  = get_canonical_labels(r_ens['canonical'], r_ens['asr'])
    p_b  = get_canonical_labels(r_base['canonical'], r_base['asr'])

    for i, (g, pe, pb) in enumerate(zip(gt, p_e, p_b)):
        if (g == pb) and (g != pe):   # c: baseline right, ensemble wrong
            span = r_ens['span_details'][i]
            print(f"canonical={span['canonical']:6}  predicted={span['predicted']:6}  winner={span['winner']}")

# 6 Results Tables

## 6.1 Summary metrics table

In [19]:
METRIC_COLS = {
    'precision':             'Precision',
    'recall':                'Recall',
    'f1':                    'F1',
    'false_acceptance_rate': 'FAR',
    'false_rejection_rate':  'FRR',
    'per':                   'PER',
}

summary_table = (
    agg_df[list(METRIC_COLS.keys())]
    .rename(columns=METRIC_COLS)
    .round(3)
)
summary_table

                          Precision  Recall     F1    FAR    FRR    PER
system
Ensemble (2-way)              0.335   0.949  0.495  0.051  0.882  1.583
Ensemble (2-way, pooled)      0.336   0.941  0.495  0.059  0.869  1.538
Ensemble (3-way)              0.335   0.950  0.495  0.050  0.882  1.586
Ensemble (3-way, pooled)      0.336   0.942  0.496  0.058  0.869  1.541
L2 model (paired)             0.358   0.856  0.505  0.144  0.717  1.107
Irish only (baseline)         0.345   0.739  0.471  0.261  0.655  0.961

## 6.2 LaTeX export

In [ ]:
print(summary_table.style.to_latex(
    caption="Mispronunciation detection results on FLEURS \\textit{ga\\_ie} evaluation set.",
    label="tab:mdd_results",
    hrules=True,
))

## 6.3 FAR / FRR figure

In [ ]:
fig, ax = plt.subplots(figsize=(7, 4))

systems = agg_df.index.tolist()
x = np.arange(len(systems))
width = 0.35

bars_far = ax.bar(x - width/2, agg_df['false_acceptance_rate'], width,
                  label='FAR (missed mispronunciations)', color='#d62728')
bars_frr = ax.bar(x + width/2, agg_df['false_rejection_rate'],  width,
                  label='FRR (false alarms)',              color='#1f77b4')

ax.set_ylabel('Rate')
ax.set_ylim(0, 1)
ax.set_xticks(x)
ax.set_xticklabels(systems, rotation=15, ha='right')
ax.legend()
ax.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1, decimals=0))
sns.despine(ax=ax)
fig.tight_layout()

fig.savefig(IMAGES_DIR / "far_frr.pdf", bbox_inches='tight')
plt.show()

# 8 Error Analysis

## 8.1 Confusion counts

In [ ]:
counts_table = agg_df[['TR', 'FA', 'FR', 'TA', 'utterances']]
counts_table

## 8.2 Confusion matrix heatmaps

In [ ]:
n = len(active_systems)
fig, axes = plt.subplots(1, n, figsize=(4 * n, 3.5))
if n == 1:
    axes = [axes]

for ax, (system_name, _) in zip(axes, active_systems.items()):
    row = agg_df.loc[system_name]
    matrix = np.array([[row['TR'], row['FA']],
                        [row['FR'], row['TA']]], dtype=int)
    sns.heatmap(matrix, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax,
                xticklabels=['Flagged', 'Accepted'],
                yticklabels=['Mispronounced', 'Correct'])
    ax.set_title(system_name, fontsize=9)
    ax.set_xlabel('Model prediction')
    ax.set_ylabel('Ground truth')

fig.tight_layout()
fig.savefig(IMAGES_DIR / "confusion_matrices.pdf", bbox_inches='tight')
plt.show()

## 8.3 Phone-level data

For each canonical phone position across all utterances, record the ground-truth label and each system's prediction. Used for the per-phoneme breakdown below.

In [ ]:
from scripts.eval.eval import get_canonical_labels

phone_rows = []
for system_name, system_records in active_systems.items():
    for r in system_records:
        gt_labels   = get_canonical_labels(r['canonical'], r['gold'])
        pred_labels = get_canonical_labels(r['canonical'], r['asr'])
        for phone, gt, pred in zip(r['canonical'], gt_labels, pred_labels):
            phone_rows.append({
                'system':        system_name,
                'phone':         phone,
                'mispronounced': gt,    # True = actually wrong (from gold)
                'flagged':       pred,  # True = model flagged it
            })

phone_df = pd.DataFrame(phone_rows)
print(f"{len(phone_df)} phone-position observations across {len(active_systems)} system(s).")

## 8.4 Per-phoneme breakdown

For the top N most frequent canonical phones: how often is each actually mispronounced (gold), and how often does each system flag it?

In [ ]:
TOP_N = 20

# Most common canonical phones across all systems (use first system to avoid duplication)
first_system = next(iter(active_systems))
top_phones = (
    phone_df[phone_df['system'] == first_system]['phone']
    .value_counts()
    .head(TOP_N)
    .index.tolist()
)

# Mispronunciation rate per phone (same across systems — comes from gold)
misp_rate = (
    phone_df[phone_df['system'] == first_system]
    .groupby('phone')['mispronounced']
    .mean()
    .reindex(top_phones)
)

# Detection rate per phone per system
det_rates = {
    name: phone_df[phone_df['system'] == name].groupby('phone')['flagged'].mean().reindex(top_phones)
    for name in active_systems
}

x = np.arange(len(top_phones))
n_systems = len(active_systems)
width = 0.6 / (n_systems + 1)

fig, ax = plt.subplots(figsize=(14, 4))

ax.bar(x, misp_rate, width, label='Mispronounced (gold)', color='#333333', alpha=0.5)
for i, (name, rates) in enumerate(det_rates.items()):
    offset = (i - (n_systems - 1) / 2) * width + width
    ax.bar(x + offset, rates, width, label=f'Flagged — {name}')

ax.set_xticks(x)
ax.set_xticklabels(top_phones, rotation=45, ha='right', fontsize=8)
ax.set_ylabel('Rate')
ax.set_ylim(0, 1)
ax.legend(fontsize=8)
sns.despine(ax=ax)
fig.tight_layout()
fig.savefig(IMAGES_DIR / "per_phoneme_breakdown.pdf", bbox_inches='tight')
plt.show()

## 8.5 Ensemble winner distribution

For each span in the ensemble, which model won (ga / en / ru)? Shows how much each model contributes.

In [ ]:
ensemble_variants = {
    name: recs for name, recs in {
        'Ensemble (2-way)': ensemble_2way_records,
        'Ensemble (3-way)': ensemble_3way_records,
    }.items() if recs is not None
}

if not ensemble_variants:
    print("No ensemble records available.")
else:
    winner_data = {}
    for name, recs in ensemble_variants.items():
        counts = {}
        for r in recs:
            for span in r['span_details']:
                w = span['winner']
                counts[w] = counts.get(w, 0) + 1
        winner_data[name] = counts

    models = sorted({m for counts in winner_data.values() for m in counts})
    x = np.arange(len(winner_data))
    width = 0.6 / len(models)
    colours = {'ga': '#2196F3', 'en': '#FF9800', 'ru': '#4CAF50'}

    fig, ax = plt.subplots(figsize=(5, 4))
    for i, model in enumerate(models):
        vals = [winner_data[name].get(model, 0) for name in winner_data]
        offset = (i - (len(models) - 1) / 2) * width
        ax.bar(x + offset, vals, width, label=model, color=colours.get(model))

    ax.set_xticks(x)
    ax.set_xticklabels(list(winner_data.keys()), rotation=10)
    ax.set_ylabel('Spans won')
    ax.legend(title='Model')
    sns.despine(ax=ax)
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "ensemble_winner_dist.pdf", bbox_inches='tight')
    plt.show()

# 8.5.1 Inspecting Russian contributions

## 8.6 Confidence score distribution

Histogram of span confidence scores split by whether the ensemble prediction matched canonical. Shows whether confidence is calibrated.

In [ ]:
if ensemble_2way_records is None:
    print("No ensemble records available.")
else:
    correct_conf   = []
    incorrect_conf = []
    for r in ensemble_2way_records:
        for span in r['span_details']:
            if span['canonical'] == span['predicted']:
                correct_conf.append(span['confidence'])
            else:
                incorrect_conf.append(span['confidence'])

    fig, ax = plt.subplots(figsize=(6, 4))
    bins = np.linspace(0, 1, 25)
    ax.hist(correct_conf,   bins=bins, alpha=0.6, label='Correct',   color='#1f77b4', density=True)
    ax.hist(incorrect_conf, bins=bins, alpha=0.6, label='Incorrect', color='#d62728', density=True)
    ax.set_xlabel('Span confidence')
    ax.set_ylabel('Density')
    ax.legend()
    sns.despine(ax=ax)
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "confidence_dist.pdf", bbox_inches='tight')
    plt.show()
    print(f"Correct spans:   {len(correct_conf):,}  (mean conf {np.mean(correct_conf):.3f})")
    print(f"Incorrect spans: {len(incorrect_conf):,} (mean conf {np.mean(incorrect_conf):.3f})")